### ISSUE TITLE
Proxy fails with TCP transport and QKD security mode

### ISSUE THREAD

**Issue by jabbarge** [ssp21/ssp21-cpp#25]
Proxy gives a ReplyHandshakeBegin error when using TCP transport and QKD security. Other combinations (TCP with preshared key and UDP with QKD) work fine. Attached are config files for initiator and responder that can be used to reproduce the error. Output logs from initiator and responder are also attached.

Also, the example config in the repo does not work as is.
[initiator-proxy.log](https://github.com/ssp21/ssp21-cpp/files/5125215/initiator-proxy.log)
[responder-proxy.log](https://github.com/ssp21/ssp21-cpp/files/5125216/responder-proxy.log)
[initiator-config-tcp.txt](https://github.com/ssp21/ssp21-cpp/files/5125223/initiator-config-tcp.txt)
[responder-config-tcp.txt](https://github.com/ssp21/ssp21-cpp/files/5125224/responder-config-tcp.txt)

**Comment by jadamcrain** [comment]
It's not super well documented, but TCP mode uses the SSP21 link layer for message framing:

https://ssp21.github.io/ssp21-cpp/mkdocs/development/proxy/configuration/#link-layer

If the link-layer addresses aren't configured correctly, the other side will just ignore your frames.

Both the initiator and responder configs have:

```
 link_layer:
      enabled: true
      address:
        local: 10
        remote: 1
```

you need to change one of them to be the opposite:

```
 link_layer:
      enabled: true
      address:
        local: 1
        remote: 10
```

I think the two will then communicate just fine.
